# Menus
menu:
  主页: .
  分类: categories
  归档: archives
  #Tags: tags
  关于: about
  开源项目: https://github.com/YunaiV/onemall

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: 
    profile:
        enabled: true # Whether to show profile bar
        fixed: true
        avatar: /css/images/avatar.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: 徐靖峰
        author_title: 阿里巴巴中间件研发
        location: 中国，杭州
        follow: /css/images/wechat_public.jpg
        wechat: /css/images/wechat_public.jpg
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: /css/images/avatar.png
    social_links:
        github: https://github.com/lexburner
        wechat: /css/images/kirito_wechat.jpeg
        rss: /atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    #- tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus:  # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # enter the domain name of your own comment isso server eg. comments.example.com
    changyan: # please fill in `appid` and `conf` to enable
        appid:
        conf:
    gitment:
        owner: lexburner
        repo: lexburner.github.io
        client_id: d5fc3e1150477a0d433d
        client_secret: aa94acd5f130281051b9e703c19b4c6d878e90c4
    livere: # enter livere uid here
    valine: # Valine Comment System https://github.com/xCss/Valine
        on:  # enter true to enable
        appId:  # enter the leancloud application appId here
        appKey: # enter the leancloud application appKey here
        notify: # enter true to enable <Mail notifier> https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
        verify: # enter true to enable <Validation code>
        placeholder: Just Do It # enter the comment box placeholder
    

# Share
share: default # options: jiathis, bdshare, addtoany, default

#是否开启打赏功能
donate: true
#打赏文案
donate_message: 大吉大利，今晚吃鸡。


# Plugins
plugins:
    lightgallery: true # options: true, false
    justified-gallery: true # options: true, false
    google_analytics: UA-118574570-1
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key


# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        namespace_ntzyz: https://ntzyz.io/
        程序猿DD|博客: http://blog.didispace.com/
        芋道源码: http://vip.iocoder.cn/
        匠心零度: http://www.jiangxinlingdu.com/
        松花皮蛋的黑板报: http://www.liangsonghua.me

