name: Deploy Hexo site to Master and Sync to Gitee

on:
  push:
    branches:
      - source
  workflow_dispatch:
  repository_dispatch:
    types: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITEE_USERNAME: xujingfeng
      GITEE_REPO_NAME: lexburner.github.io
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          ref: source
          submodules: true

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npx hexo generate

      - name: Deploy to GitHub master branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          force_orphan: true

      - name: Push to Gitee master branch
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          cd public
          git init
          git checkout --orphan master
          git add -A
          git commit -m "Deploy to Gitee"
          
          git push --force https://${GITEE_USERNAME}:${GITEE_TOKEN}@gitee.com/${GITEE_USERNAME}/${GITEE_REPO_NAME}.git master:master